# Generated by Django 5.1.3 on 2024-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(verbose_name="Дата и время запуска"),
        ),
    ]
