# Generated by Django 5.1.3 on 2024-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Ф.И.О."),
        ),
    ]
